### PR TITLE
Prevent `/` in filePath be encoded.

### PR DESCRIPTION
**Pull request by ipcjs**
convert
`https://github.com/fabiospampinato/vscode-open-in-github/blob/master/src%2Fcommands.ts/#L119`
to
`https://github.com/fabiospampinato/vscode-open-in-github/blob/master/src/commands.ts/#L119`

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Both urls seem to be working so I'm not sure why this should be changed 🤔

**Comment by ipcjs** [comment]
But `%2F` is not human friendly.

**Comment by ipcjs** [comment]
Are you considering merging this pr?

**Comment by fabiospampinato** [comment]
> Are you considering merging the PR?

Yes otherwise I would have closed.

Available in v1.2.2.

**Pull request merged**
