### PR TITLE
Fix two bugs

### PR DESCRIPTION
**Pull request by usama8800**

### CODE REVIEW

**Comment by fabiospampinato** [comment]
How do I reproduce those bugs?

**Comment by usama8800** [comment]
One of them is just that if the settings"useLocalBranch" is true, it doesn't use local branch and opens a fixed remote branch. 

The other one I didn't know existed when I came to fix the previous one but I just saw the code. If the remote url doesn't exist, it was supposed stop with a msg by checking if repeurl undefined but you were checking repopath again

**Comment by usama8800** [comment]
You should see the commit. It's just two lines

**Comment by fabiospampinato** [comment]
Thanks, available in v1.2.1.

**Pull request merged**
